use tempfile instead of namefixed one
opendevstack/tailor pull request #244
Opened 2021-12-16 15:32 UTC by clemensutschig

closes #243 for master

2021-12-16 16:17 UTC, michaelsauter commented on pkg/openshift/template.go
> +			log.Fatal(err)
`log` is not imported - better to return the error anyway I think: `return []byte{}, err`

2021-12-16 16:17 UTC, michaelsauter commented on pkg/openshift/template.go
> +		err = tempParamFile.Write(paramFileBytes)
`Write` returns two values

2021-12-17 07:14 UTC, michaelsauter requested changes
Thanks a lot!

One minor suggested change to return an error - could happen if the temp dir is not writable by the current user.

2021-12-17 07:14 UTC, michaelsauter commented on pkg/openshift/template.go
> +		tempParamFile,_ := ioutil.TempFile("", ".combined.*.env")
```suggestion
		tempParamFile, err := ioutil.TempFile("", ".combined.*.env")
		if err != nil {
				return []byte{}, err
		}
```

2021-12-17 09:35 UTC, michaelsauter approved these changes

2021-12-17 09:35 UTC, merged

2021-12-17 12:53 UTC, clemensutschig commented
@michaelsauter - do you burn a new release?

2021-12-17 12:59 UTC, michaelsauter commented
@clemensutschig Already done: https://github.com/opendevstack/tailor/releases/tag/v1.3.3 :)

I will open PRs for inclusion into the Jenkins base agent as well.